'use strict';

window.TRANSLATIONS = window.TRANSLATIONS || {};
window.TRANSLATIONS.en = {
  nav: {
    how: 'How It Works',
    advantages: 'Advantages',
    categories: 'What We Buy',
    reviews: 'Reviews',
    contacts: 'Contacts'
  },
  hero: {
    badge: 'Kyiv & region — on-site in 2 hrs',
    headline_1: 'We buy',
    headline_2: 'your',
    headline_3: 'equipment',
    headline_4: 'today',
    sub: 'Professional buyout of HoReCa kitchen equipment and furniture. Arrival, valuation and payment — all in one day. No haggling, no delays.',
    cta: 'Get a Quote',
    cta2: 'How It Works',
    stat_buyouts: 'visits',
    stat_years: 'years exp.',
    stat_hours: 'hr estimate'
  },
  how: {
    label: 'Process',
    title_1: 'How it',
    title_2: 'works',
    desc: 'From inquiry to cash in hand — four simple steps. No bureaucracy, no hassle.',
    step1_title: 'Submit a request',
    step1_desc: 'Fill in the form or call us. Specify the type and approximate volume of equipment.',
    step2_title: 'Estimate in 2 hrs',
    step2_desc: 'Our appraiser will contact you and provide an estimated value within two hours.',
    step3_title: 'On-site inspection',
    step3_desc: 'We arrive at a time convenient for you, inspect the equipment and confirm the price.',
    step4_title: 'Payment on site',
    step4_desc: 'Pickup, dismantling and loading — at our expense. You receive payment immediately.'
  },
  about: {
    label: 'About us',
    title_1: 'Not a flea market.',
    title_2: 'Business.',
    p1: '<strong>KITO</strong> is a team of specialists in the secondary HoReCa equipment market. We resell equipment to other venues, so we know the real market value and pay a fair price.',
    p2: 'Our clients are restaurants, cafes and bars that are closing or upgrading their kitchens. We understand that every day of downtime means losses. That\'s why we act fast.',
    p3: '<strong>Over 5 years</strong> in the Kyiv and Kyiv region market. More than 500 visits and not a single unanswered request.',
    cta: 'Book a Visit',
    fact1_val: '500+',
    fact1_label: 'Successful deals',
    fact2_val: '5+',
    fact2_label: 'Years on market',
    fact3_val: '24h',
    fact3_label: 'Estimate time',
    fact4_val: '₴0',
    fact4_label: 'Visit cost'
  },
  advantages: {
    label: 'Why KITO',
    title_1: 'Our',
    title_2: 'advantages',
    card1_title: 'Estimate in 2 hrs',
    card1_desc: 'A call or message — and you already know the price. No waiting a week.',
    card2_title: 'Pickup & loading',
    card2_desc: 'We arrive with a team and cargo vehicle. Dismantling and removal — at our expense.',
    card3_title: 'Direct payment',
    card3_desc: 'Cash or bank transfer — immediately after signing the act. No delays.',
    card4_title: 'Consignment option',
    card4_desc: 'No urgent sale needed — we arrange consignment and pay you after the item sells.'
  },
  categories: {
    label: 'What we buy',
    title_1: '8 categories',
    title_2: 'of equipment',
    desc: 'We buy any HoReCa equipment — from coffee machines to industrial extraction systems.',
    cat1: 'Refrigeration equipment',
    cat2: 'Thermal / cooking',
    cat3: 'Coffee machines / bar',
    cat4: 'Dishwashing',
    cat5: 'HoReCa furniture',
    cat6: 'Tableware & inventory',
    cat7: 'Ventilation',
    cat8: 'Other equipment'
  },
  reviews: {
    label: 'Client reviews',
    title_1: 'What our',
    title_2: 'clients say',
    r1_text: 'I was closing my café after 10 years. I called KITO in the morning — the team arrived by evening. They took the entire kitchen and paid in cash. Very convenient and no unnecessary questions.',
    r1_name: 'Oleg Mykhailenko',
    r1_role: 'Owner of café «Warm Time», Kyiv',
    r2_text: 'We were upgrading the kitchen in our restaurant — nowhere to put the old equipment. KITO appraised the fridges and cookers online, arrived the next morning. Fair price, efficient work.',
    r2_name: 'Iryna Bondarenko',
    r2_role: 'Manager of restaurant «Levant», Boryspil',
    r3_text: 'I thought nobody would want old furniture and bar equipment. But KITO took everything and paid more than I expected. I recommend them to anyone closing down or relocating.',
    r3_name: 'Maksym Tkachenko',
    r3_role: 'Owner of bar «Craft & Chill», Kyiv',
    r4_text: 'I came with a non-standard request — premium-class coffee machines. They appraised correctly, movers packed carefully. No damage whatsoever. All clear and as agreed.',
    r4_name: 'Valeria Sydorenko',
    r4_role: 'Director of coffee shop «Volta», Vyshhorod',
    aria_stars: 'Rating 5 out of 5'
  },
  contacts: {
    label: 'Get in touch',
    title: 'Contacts',
    block_title: 'Reach us in any convenient way',
    phone_label: 'Phone',
    telegram_label: 'Telegram',
    viber_label: 'Viber',
    address_label: 'Service area',
    address_value: 'Kyiv & Kyiv region',
    map_aria: 'Location map',
    map_city: 'Kyiv & Kyiv region',
    map_note: 'Map will be connected after launch'
  },
  form: {
    promo_title_1: 'Get a',
    promo_title_2: 'free',
    promo_title_3: 'estimate',
    promo_desc: 'Submit a request and our specialist will call within 1 hour during business hours. Pickup and loading — free of charge.',
    guarantee: 'Your data will not be shared with third parties',
    label_name: 'Your name',
    label_phone: 'Phone',
    label_equipment: 'Equipment type',
    label_comment: 'Comment',
    placeholder_name: 'Ivan Petrenko',
    placeholder_phone: '+38 (0XX) XXX-XX-XX',
    placeholder_equipment: 'Select a category',
    placeholder_comment: 'Describe the equipment: brand, condition, quantity...',
    submit: 'Send request',
    submitting: 'Sending...',
    disclaimer: 'By clicking the button you agree to the processing of personal data',
    error_name: 'Please enter your name',
    error_phone: 'Please enter a valid +38 number',
    error_equipment: 'Please select equipment type',
    success_title: 'Request received!',
    success_text: 'We will contact you within 1 hour during business hours. Thank you!'
  },
  footer: {
    brand_desc: 'On-site buyout of HoReCa kitchen equipment and furniture. Kyiv & Kyiv region. Estimate in 2 hrs, payment on site.',
    nav_title: 'Navigation',
    contacts_title: 'Contacts',
    link_how: 'How It Works',
    link_about: 'About Us',
    link_advantages: 'Advantages',
    link_categories: 'What We Buy',
    link_reviews: 'Reviews',
    link_form: 'Submit a request',
    copy: '© 2024–2025',
    copy_region: 'Kyiv & Kyiv region'
  },
  misc: {
    scroll_top: 'Scroll to top',
    menu_aria: 'Menu',
    mobile_menu_aria: 'Mobile menu',
    nav_aria: 'Navigation'
  }
};
